# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCronjobTimetable < Formula
  desc "Display a timetable of CronJob's schedule"
  homepage "https://github.com/unblee/kubectl-cronjob-timetable"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/unblee/kubectl-cronjob-timetable/releases/download/0.1.0/kubectl-cronjob-timetable_darwin_amd64.tar.gz"
    sha256 "179988190b42e5ab29af6ccd4beca5d8baf2b7f3c7942f29187de331457966d9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/unblee/kubectl-cronjob-timetable/releases/download/0.1.0/kubectl-cronjob-timetable_linux_amd64.tar.gz"
      sha256 "ae0b6761863af5746c351bd5f13f59cc8d7f346385b5c9e380729f59728dedfa"
    end
  end

  def install
    bin.install "kubectl-cronjob-timetable"
  end
end
