# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCls < Formula
  desc "List CronJobs and CronWorkflows that are scheduled and executed during a specific time period."
  homepage "https://github.com/unblee/kubectl-cls"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.2/kubectl-cls_Darwin_arm64.tar.gz"
      sha256 "e76eb4eff8d8ae7977f7c7c1aff9560ce2a05916cf10fd3a08731ce8af2e714b"

      def install
        bin.install "kubectl-cls"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.2/kubectl-cls_Darwin_x86_64.tar.gz"
      sha256 "dd94e6ed54377574068de466f3328868f3024e3f7a234949770a313cd31b079d"

      def install
        bin.install "kubectl-cls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.2/kubectl-cls_Linux_x86_64.tar.gz"
      sha256 "eb457bdc87faa3daaf1b5a2699b6189a370b15016bce2950ee92b1f2a51f3784"

      def install
        bin.install "kubectl-cls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.2/kubectl-cls_Linux_arm64.tar.gz"
      sha256 "96e4769d7f0e035dad17f46c899210e370f9d427caf399fdc58af91d834e2d1a"

      def install
        bin.install "kubectl-cls"
      end
    end
  end
end
