# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCls < Formula
  desc "List CronJobs and CronWorkflows that are scheduled and executed during a specific time period."
  homepage "https://github.com/unblee/kubectl-cls"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.0/kubectl-cls_Darwin_arm64.tar.gz"
      sha256 "bd9205c5d91709956a866abea2f8ca39bbf3b91c102f04b4473b98391d19a685"

      def install
        bin.install "kubectl-cls"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.0/kubectl-cls_Darwin_x86_64.tar.gz"
      sha256 "034eec3d7c70f050ffc973503ff06098de569664dc1bb6e9a48ed490f25a14dc"

      def install
        bin.install "kubectl-cls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.0/kubectl-cls_Linux_x86_64.tar.gz"
      sha256 "77fc38493c417614aa9526122c9bd175e4eaa997e24e4b84929ad1b71237efae"

      def install
        bin.install "kubectl-cls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unblee/kubectl-cls/releases/download/v1.0.0/kubectl-cls_Linux_arm64.tar.gz"
      sha256 "9d2763d675b1b3c22f070c99cfbfb183a7bc5b8a5ac1a3dc428d9ee4ef312a76"

      def install
        bin.install "kubectl-cls"
      end
    end
  end
end
